### ISSUE TITLE
Pull Requests run `publish.yml` action

### ISSUE THREAD

**Issue by jan-david-fischbach** [gdsfactory/sax#41]
Hey @flaport,
I think we should avoid running the publish action on PRs (as it will inevitably fail).
Or was there some reason behind setting it up this way?

To change this behavior we would only have to change this line:
https://github.com/flaport/sax/blob/aabd9f9c9d8bf97c65f30cba5fe87cfac466fd84/.github/workflows/publish.yml#L4

Should I open a PR?

Regards
JD

**Comment by flaport** [comment]
Thanks for noticing @jan-david-fischbach . I fixed it :)
