### ISSUE TITLE
simulate hierachical components

### ISSUE THREAD

**Issue by joamatab** [gdsfactory/sax#9]
How can we simulate hierarchical components?

See for example 2 mzis connected to each other

**Comment by joamatab** [comment]
I added an example here

https://github.com/gdsfactory/gdsfactory/blob/master/fixme/circuit_simulations_fixme.py

**Comment by flaport** [comment]
This was implemented today: sax>=0.8.0.

Note that this is a breaking change. Your notebooks depending on SAX will likely break. But what we get in return is a much better pydantic-based netlist parser and a better circuit resolver. 

I'll fix the example notebooks in gdsfactory soon.

**Comment by flaport** [comment]
see:

- https://flaport.github.io/sax/nbs/06_netlist.html
- https://flaport.github.io/sax/nbs/08_circuit.html

**Comment by joamatab** [comment]
Awesome. Thank you Floris
